import { PrismaClient } from "@prisma/client";
import { getRubricEntries } from "../lib/seed-data/scoring-rubric";
import { INDUSTRIES, getIndustryDimensionWeights } from "../lib/seed-data/industries";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // 1. Scoring rubric (8 dimensions × 5 ranges = 40 entries)
  await prisma.scoringRubric.deleteMany({});
  const rubricEntries = getRubricEntries();
  await prisma.scoringRubric.createMany({
    data: rubricEntries.map(({ dimension, scoreRange, criteria }) => ({
      dimension,
      scoreRange,
      criteria: criteria as object,
    })),
  });
  console.log(`  Created ${rubricEntries.length} scoring rubric entries.`);

  // 2. Industries (20) - merge dimensionWeights into scoringCriteria
  for (const ind of INDUSTRIES) {
    const scoringCriteriaWithWeights = {
      ...ind.scoringCriteria,
      dimensionWeights: getIndustryDimensionWeights(ind),
    };
    await prisma.industry.upsert({
      where: { name: ind.name },
      create: {
        name: ind.name,
        description: ind.description,
        scoringCriteria: scoringCriteriaWithWeights as object,
        preferredTemplates: [],
      },
      update: {
        description: ind.description,
        scoringCriteria: scoringCriteriaWithWeights as object,
      },
    });
  }
  console.log(`  Created/updated ${INDUSTRIES.length} industries.`);

  // 3. Default app settings
  await prisma.appSetting.upsert({
    where: { key: "analysis_cooldown_days" },
    create: { key: "analysis_cooldown_days", value: "30" },
    update: {},
  });
  console.log("  Seeded default app settings.");

  // 4. Delivery platforms
  const platforms = [
    {
      key: "html",
      label: "Generic HTML",
      sortOrder: 0,
      sectionSplit: false,
      platformNotes: "Self-contained HTML file with inline CSS. Works with any host — Netlify, Vercel, GitHub Pages, or hand off to a developer.",
      folderStructure: JSON.stringify({
        files: ["README.txt", "index.html"],
        dirs: ["assets/", "assets/brand/"],
      }),
      readmeTemplate: `# {businessName} — Refreshed Layout

Generated by Page Refresh for {siteUrl}
Template: {templateName}
Platform: {targetPlatform}

## Quick Start

Open index.html in your browser to preview the layout.
Upload the entire folder to your hosting provider.

## Files

- index.html — Your complete refreshed page
- assets/ — Images and media referenced in the layout
- assets/brand/colors.css — Your brand color variables

## Brand Colors

Primary: {primaryColor}

## Download Link

{downloadUrl}

---
Refreshed by Page Refresh · https://pagerefresh.ai`,
    },
    {
      key: "wordpress",
      label: "WordPress",
      sortOrder: 1,
      sectionSplit: false,
      platformNotes: "Includes a custom page template (.php) that appears in Page Attributes in the WordPress editor. Paste additional-css.css into Appearance > Customize > Additional CSS.",
      folderStructure: JSON.stringify({
        files: ["README.txt", "page-template.php", "additional-css.css"],
        dirs: ["assets/"],
      }),
      readmeTemplate: `# {businessName} — WordPress Layout

Generated by Page Refresh for {siteUrl}
Template: {templateName}

## Installation

1. Upload page-template.php to your theme folder: wp-content/themes/your-theme/
2. In WordPress admin: Pages > Add New > Page Attributes > Template > select "PageRefresh Layout"
3. Copy the contents of additional-css.css
4. Go to Appearance > Customize > Additional CSS and paste

## Files

- page-template.php — WordPress page template
- additional-css.css — Styles for Appearance > Customize > Additional CSS
- assets/ — Images and media

## Brand Colors

Primary: {primaryColor}
Detected CMS: {detectedCMS}

---
Refreshed by Page Refresh · https://pagerefresh.ai`,
    },
    {
      key: "squarespace",
      label: "Squarespace",
      sortOrder: 2,
      sectionSplit: true,
      platformNotes: "Squarespace does not support full-page HTML imports. Each file in the /sections folder must be added as a separate Code Block via the page editor (Edit Page > Add Block > Code). The css-injection.css file should be pasted into Settings > Advanced > Code Injection, wrapped in <style> tags.",
      folderStructure: JSON.stringify({
        files: ["README.txt", "css-injection.css", "full-preview.html"],
        dirs: ["sections/", "assets/"],
      }),
      readmeTemplate: `# {businessName} — Squarespace Layout

Generated by Page Refresh for {siteUrl}
Template: {templateName}

## Installation

1. Go to Settings > Advanced > Code Injection
2. Paste the contents of css-injection.css wrapped in <style> tags into the Header section
3. Edit the page where you want the layout
4. For each file in sections/ (in order):
   - Add Block > Code
   - Paste the HTML contents
   - Toggle "Display Source" OFF

## Important

Do NOT attempt to import full-preview.html directly into Squarespace.
The sections/ folder contains your layout split into individual blocks.

## Files

- css-injection.css — Paste into Code Injection (wrapped in <style> tags)
- sections/ — Individual code blocks, numbered in order
- full-preview.html — Reference only (open in browser to preview)
- assets/ — Images and media

---
Refreshed by Page Refresh · https://pagerefresh.ai`,
    },
    {
      key: "wix",
      label: "Wix",
      sortOrder: 3,
      sectionSplit: false,
      platformNotes: "Wix has significant limitations for custom HTML. The embed-version.html works via the Wix Embed HTML widget (Add > Embed > Embed a Widget). For full-page replacement, enable Wix Developer Mode and use the /velo/page-code.js file.",
      folderStructure: JSON.stringify({
        files: ["README.txt", "embed-version.html", "full-preview.html"],
        dirs: ["velo/", "assets/"],
      }),
      readmeTemplate: `# {businessName} — Wix Layout

Generated by Page Refresh for {siteUrl}
Template: {templateName}

## Option A: Embed Widget (Simplest)

1. In Wix Editor: Add > Embed > Embed a Widget
2. Paste the contents of embed-version.html
3. Resize the widget to fill the page

## Option B: Velo Developer Mode (Advanced)

1. Enable Wix Developer Mode: Manage > Developer Tools
2. Copy velo/page-code.js into your page code
3. Follow the comments in the file for setup

## Files

- embed-version.html — Self-contained for iframe embed
- velo/page-code.js — For Wix Developer Mode
- full-preview.html — Reference (open in browser to preview)
- assets/ — Images and media

---
Refreshed by Page Refresh · https://pagerefresh.ai`,
    },
    {
      key: "webflow",
      label: "Webflow",
      sortOrder: 4,
      sectionSplit: false,
      platformNotes: "Paste the contents of index.html into a Webflow Embed element, or use Webflow's Custom Code panel under Page Settings. CSS goes into Site Settings > Custom Code > Head Code wrapped in <style> tags.",
      folderStructure: JSON.stringify({
        files: ["README.txt", "index.html", "styles.css"],
        dirs: ["assets/"],
      }),
      readmeTemplate: `# {businessName} — Webflow Layout

Generated by Page Refresh for {siteUrl}
Template: {templateName}

## Installation

1. In Webflow: Site Settings > Custom Code > Head Code
2. Paste the contents of styles.css wrapped in <style> tags
3. On your page: Add an Embed element
4. Paste the contents of index.html

For a cleaner integration, a developer can use the HTML structure as a reference to rebuild in Webflow's visual editor.

## Files

- index.html — Layout HTML for Embed element
- styles.css — CSS for Site Settings > Custom Code
- assets/ — Images and media

---
Refreshed by Page Refresh · https://pagerefresh.ai`,
    },
  ];

  for (const p of platforms) {
    await prisma.deliveryPlatform.upsert({
      where: { key: p.key },
      create: p,
      update: {
        label: p.label,
        sortOrder: p.sortOrder,
        sectionSplit: p.sectionSplit,
        platformNotes: p.platformNotes,
        folderStructure: p.folderStructure,
        readmeTemplate: p.readmeTemplate,
      },
    });
  }
  console.log(`  Created/updated ${platforms.length} delivery platforms.`);

  console.log("Seed completed.");
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
