/**
 * 20 industries with scoring criteria for the 8 universal dimensions.
 * Used to seed the Industry table and for industry-aware scoring.
 */

export interface IndustrySeed {
  name: string;
  description: string;
  scoringCriteria: Record<
    string,
    { weight: number; indicators: string[]; antipatterns: string[] }
  >;
  preferredTemplates: string[]; // Template names; resolved to IDs in seed
}

export const INDUSTRIES: IndustrySeed[] = [
  {
    name: "Accountants",
    description: "CPA firms, bookkeepers, tax preparers, and accounting practices",
    scoringCriteria: {
      clarity: {
        weight: 1.0,
        indicators: ["Clear services listed (tax, bookkeeping, advisory)", "Specialization stated", "Target audience obvious (SMB, individuals)"],
        antipatterns: ["Vague 'full service' claims", "No differentiation from competitors"],
      },
      visual: { weight: 1.0, indicators: ["Professional, conservative design", "Trustworthy color palette"], antipatterns: ["Overly flashy or casual"] },
      hierarchy: { weight: 1.0, indicators: ["Services clearly sectioned", "Credentials prominent"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Credentials (CPA, licenses)", "Client types or industries", "Testimonials or case studies"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Clear 'Schedule consultation' or 'Get quote' CTA"], antipatterns: [] },
      content: { weight: 1.0, indicators: ["Plain language", "Benefit-focused"], antipatterns: ["Heavy jargon"] },
      mobile: { weight: 1.0, indicators: ["Readable on phone", "Easy contact tap"], antipatterns: [] },
      performance: { weight: 1.0, indicators: ["Fast load", "HTTPS"], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "features-grid", "testimonials-carousel"],
  },
  {
    name: "Lawyers",
    description: "Law firms, solo practitioners, and legal practices",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Practice areas clear", "Who you help (e.g., injured, businesses)"], antipatterns: ["Generic 'we fight for you'"] },
      visual: { weight: 1.0, indicators: ["Professional, authoritative"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Practice areas scannable", "Case results or wins"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Bar admissions", "Awards", "Testimonials", "Case results"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Free consultation CTA", "Clear contact"], antipatterns: [] },
      content: { weight: 1.0, indicators: ["Clear and empathetic", "No legalese on homepage"], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "features-grid", "testimonials-carousel"],
  },
  {
    name: "Golf Courses",
    description: "Golf courses, country clubs, and golf facilities",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Course info", "Tee times", "Amenities"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Quality course imagery", "Clean layout"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Rates, hours, booking path clear"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Reviews", "Awards", "History"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Book tee time CTA", "Contact"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: ["Mobile booking friendly"], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "dual-demo-screenshots", "features-grid"],
  },
  {
    name: "Beauty Salons",
    description: "Hair salons, spas, and beauty studios",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Services (hair, nails, etc.)", "Pricing or menu"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Stylish, on-brand imagery", "Portfolio or gallery"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Services sectioned", "Booking prominent"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Stylist bios", "Reviews", "Before/after"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Book online CTA"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: ["Easy booking on phone"], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "ios-card-fan", "testimonials-carousel"],
  },
  {
    name: "Barbershops",
    description: "Barbershops and men's grooming",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Services", "Walk-in vs appointment"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Strong brand aesthetic", "Shop/team photos"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Services and pricing clear"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Barber bios", "Social proof"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Book or visit CTA"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "logo-marquee", "testimonials-carousel"],
  },
  {
    name: "Homeowner Associations (HOAs)",
    description: "HOA management and community associations",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["What the HOA does", "Resident resources", "Board/contact"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Professional, community-oriented"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Documents, meetings, dues clear"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Transparency", "Governing docs", "Contact info"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Pay dues", "Submit request", "Contact"], antipatterns: [] },
      content: { weight: 1.0, indicators: ["Plain language", "Scannable"], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["features-grid", "dual-hero", "switch-provider-cta"],
  },
  {
    name: "Veterinary Clinics",
    description: "Vet clinics and animal hospitals",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Services (wellness, surgery, etc.)", "Hours and location"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Warm, caring imagery", "Clean and professional"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Services and pricing", "New client info"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Vet bios", "Reviews", "Accreditations"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Request appointment", "Contact"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "features-grid", "testimonials-carousel"],
  },
  {
    name: "Property Management",
    description: "Property management companies and landlords",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Services (rental, maintenance)", "Who they serve (owners/tenants)"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Professional", "Property imagery"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Services", "Listings or portal"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Reviews", "Portfolio", "Licenses"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["List property", "Contact", "Tenant portal"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "dual-demo-screenshots", "features-grid"],
  },
  {
    name: "Funeral Homes",
    description: "Funeral homes and memorial services",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Services (traditional, cremation, etc.)", "Compassionate tone"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Respectful, calm design", "Dignified imagery"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Services", "Planning", "Contact"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Staff", "Facility", "Affiliations"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Pre-plan", "Contact", "Obituaries"], antipatterns: [] },
      content: { weight: 1.0, indicators: ["Sensitive, clear language"], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "features-grid", "saas-about-page"],
  },
  {
    name: "Daycares",
    description: "Childcare centers and preschools",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Age groups", "Programs", "Hours and location"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Warm, child-friendly", "Photos of facility/kids"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Programs", "Enrollment", "Tuition"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Licensing", "Staff", "Testimonials"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Schedule tour", "Enroll"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "features-grid", "testimonials-carousel"],
  },
  {
    name: "Lawn Care & Landscaping",
    description: "Lawn care, landscaping, and outdoor services",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Services (mowing, design, etc.)", "Service area"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Before/after", "Portfolio"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Services and pricing", "Get quote"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Reviews", "Certifications", "Insurance"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Free estimate", "Contact"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "dual-demo-screenshots", "features-grid"],
  },
  {
    name: "Insurance Agencies",
    description: "Insurance agents and brokers",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Lines (auto, home, life, etc.)", "Who they serve"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Professional", "Trustworthy"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Products", "Get quote path"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Carriers", "Licenses", "Reviews"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Get quote", "Request call"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "switch-provider-cta", "testimonials-carousel"],
  },
  {
    name: "Gun Clubs",
    description: "Shooting ranges and gun clubs",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Facilities", "Membership", "Hours"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Professional", "Facility photos"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Membership tiers", "Safety", "Contact"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Safety focus", "Affiliations"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Join", "Visit", "Contact"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "features-grid", "logo-marquee"],
  },
  {
    name: "Community Theatres",
    description: "Community theaters and performing arts",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Season/shows", "Get tickets", "Support"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Creative", "Show imagery"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Shows", "Tickets", "About"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Reviews", "History", "Partners"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Buy tickets", "Donate", "Subscribe"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "ios-card-fan", "testimonials-carousel"],
  },
  {
    name: "Dentists",
    description: "Dental practices and orthodontists",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Services", "New patients", "Hours"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Clean, professional", "Office/team"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Services", "Insurance", "Contact"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Doctor bios", "Reviews", "Technology"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Request appointment", "New patient form"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "features-grid", "testimonials-carousel"],
  },
  {
    name: "Real Estate Agents",
    description: "Realtors and real estate professionals",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Service area", "Buy/sell/rent", "Listings"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["High-quality listing photos", "Professional"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Listings", "About", "Contact"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Sales record", "Reviews", "Credentials"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Search listings", "Contact", "Home value"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: ["Mobile-friendly listings"], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "dual-demo-screenshots", "features-grid"],
  },
  {
    name: "Restaurants",
    description: "Restaurants, cafes, and food service",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Cuisine", "Menu", "Hours and location"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Food imagery", "Ambiance", "Modern design"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Menu", "Reservations", "Contact"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Reviews", "Awards", "Chef/story"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Reserve", "Order", "Directions"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: ["Menu and reserve on mobile"], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "ios-card-fan", "testimonials-carousel"],
  },
  {
    name: "Fitness Studios",
    description: "Gyms, yoga studios, and fitness centers",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Classes/programs", "Schedule", "Pricing"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Energetic", "Studio/class imagery"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Classes", "Pricing", "Trial"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Instructor bios", "Reviews", "Facility"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Free trial", "Join", "Book class"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "features-grid", "testimonials-carousel"],
  },
  {
    name: "Auto Repair",
    description: "Auto repair shops and mechanics",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Services", "Specialties", "Hours"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Professional", "Shop/team"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Services", "Pricing", "Contact"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Certifications", "Reviews", "Warranty"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Schedule service", "Get quote", "Contact"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "switch-provider-cta", "features-grid"],
  },
  {
    name: "General Contractors",
    description: "General contractors and construction",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Services (remodel, build, etc.)", "Service area"], antipatterns: [] },
      visual: { weight: 1.0, indicators: ["Portfolio", "Before/after", "Professional"], antipatterns: [] },
      hierarchy: { weight: 1.0, indicators: ["Services", "Projects", "Contact"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Licenses", "Insurance", "Reviews", "Portfolio"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Free estimate", "Contact"], antipatterns: [] },
      content: { weight: 1.0, indicators: [], antipatterns: [] },
      mobile: { weight: 1.0, indicators: [], antipatterns: [] },
      performance: { weight: 1.0, indicators: [], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "dual-demo-screenshots", "features-grid"],
  },
  {
    name: "General Business",
    description: "Fallback for low-confidence or ambiguous industry detection",
    scoringCriteria: {
      clarity: { weight: 1.0, indicators: ["Clear value proposition", "Target audience", "Clear CTA"], antipatterns: ["Vague messaging", "No CTA"] },
      visual: { weight: 1.0, indicators: ["Professional design", "Clean layout"], antipatterns: ["Cluttered", "Dated"] },
      hierarchy: { weight: 1.0, indicators: ["Logical flow", "Scannable sections"], antipatterns: [] },
      trust: { weight: 1.0, indicators: ["Contact info", "Social proof", "Credentials"], antipatterns: [] },
      conversion: { weight: 1.0, indicators: ["Clear next step", "Visible CTA"], antipatterns: [] },
      content: { weight: 1.0, indicators: ["Readable", "Benefit-focused"], antipatterns: ["Jargon-heavy"] },
      mobile: { weight: 1.0, indicators: ["Mobile-friendly"], antipatterns: [] },
      performance: { weight: 1.0, indicators: ["Fast load", "HTTPS"], antipatterns: [] },
    },
    preferredTemplates: ["dual-hero", "features-grid", "testimonials-carousel"],
  },
];
