/**
 * Platform-specific layout exports (ZIP packages for self-installers).
 */

import archiver from "archiver";
import { Writable } from "stream";

export type Platform = "html" | "squarespace" | "wordpress" | "wix";

export interface ExportResult {
  filename: string;
  buffer: Buffer;
  contentType: string;
}

export interface ExportMetadata {
  url: string;
  industry: string;
}

function bufferFromStream(
  archive: archiver.Archiver
): Promise<Buffer> {
  const chunks: Buffer[] = [];
  const collector = new Writable({
    write(chunk: Buffer | string, _enc, cb) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk, "utf-8"));
      cb();
    },
  });
  archive.pipe(collector);
  return new Promise((resolve, reject) => {
    collector.on("finish", () => resolve(Buffer.concat(chunks)));
    archive.on("error", reject);
  });
}

function addReadme(
  archive: archiver.Archiver,
  platform: string,
  content: string
): void {
  archive.append(Buffer.from(content, "utf-8"), { name: "README.md" });
}

/** Full standalone HTML document with embedded CSS so the zip has something you can open to see the layout. */
function buildPreviewDocument(layoutHtml: string, layoutCss: string): string {
  const trimmed = layoutHtml.trim();
  const isFullDocument =
    trimmed.startsWith("<!") || trimmed.toLowerCase().startsWith("<html");
  if (isFullDocument) {
    return trimmed.replace(
      /<\/head\s*>/i,
      `<style>\n${layoutCss}\n</style>\n</head>`
    );
  }
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Layout preview – pagerefresh.ai</title>
  <style>
${layoutCss}
  </style>
</head>
<body>
${layoutHtml}
</body>
</html>`;
}

export async function exportLayout(
  platform: Platform,
  layoutHtml: string,
  layoutCss: string,
  templateName: string,
  metadata: ExportMetadata
): Promise<ExportResult> {
  const safeName = templateName.replace(/[^a-z0-9-_]/gi, "-").toLowerCase();
  const filename = `pagerefresh-layout${safeName}-${platform}.zip`;
  const archive = archiver("zip", { zlib: { level: 9 } });

  const bufferPromise = bufferFromStream(archive);

  const fullHtml =
    layoutHtml.trim().startsWith("<!") ||
    layoutHtml.trim().toLowerCase().startsWith("<html")
      ? layoutHtml
      : `<!DOCTYPE html><html><head><meta charset="utf-8"><link rel="stylesheet" href="styles.css"></head><body>${layoutHtml}</body></html>`;

  switch (platform) {
    case "html": {
      const htmlForExport =
        fullHtml.includes("styles.css") ? fullHtml : fullHtml.replace("</head>", "<link rel=\"stylesheet\" href=\"styles.css\"></head>");
      archive.append(Buffer.from(htmlForExport, "utf-8"), {
        name: "index.html",
      });
      archive.append(Buffer.from(layoutCss, "utf-8"), { name: "styles.css" });
      addReadme(
        archive,
        "html",
        `# Full Page Export – HTML/CSS\n\nGenerated by [pagerefresh.ai](https://pagerefresh.ai)\n\nThis zip contains the **full page** (all sections). Upload these files to build your full site.\n\n## Setup\n\n1. Upload \`index.html\` and \`styles.css\` to your web host or static hosting.\n2. Ensure paths to fonts/images match your setup (update any YOUR_* placeholders if present).\n\nOriginal site: ${metadata.url} | Industry: ${metadata.industry}\n`
      );
      break;
    }
    case "wordpress": {
      const themeName = `PageRefresh ${safeName}`;
      const styleCss = `/*
Theme Name: ${themeName}
Description: Homepage layout generated by pagerefresh.ai
Author: pagerefresh.ai
Version: 1.0
*/
${layoutCss}`;
      archive.append(Buffer.from(styleCss, "utf-8"), { name: "style.css" });
      const indexPhp = `<?php
/**
 * Template Name: PageRefresh Layout
 * Generated by pagerefresh.ai
 */
get_header();
?>
${layoutHtml}
<?php
get_footer();
`;
      archive.append(Buffer.from(indexPhp, "utf-8"), { name: "index.php" });
      const functionsPhp = `<?php
/**
 * Enqueue theme styles – pagerefresh.ai
 */
function pagerefresh_enqueue_styles() {
  wp_enqueue_style('pagerefresh-layout', get_stylesheet_uri());
}
add_action('wp_enqueue_scripts', 'pagerefresh_enqueue_styles');
`;
      archive.append(Buffer.from(functionsPhp, "utf-8"), {
        name: "functions.php",
      });
      addReadme(
        archive,
        "wordpress",
        `# WordPress Theme Export – Full Page\n\nGenerated by [pagerefresh.ai](https://pagerefresh.ai)\n\nThis zip contains the **full page** layout. Use it to build your full site in WordPress.\n\n## Upload\n\n1. Zip this folder (if you received individual files, ensure style.css, index.php, functions.php are in the root of the ZIP).\n2. In WordPress: Appearance → Themes → Add New → Upload Theme.\n3. Choose the ZIP and Activate (or use as a child theme).\n4. Create a Page and set Template to "PageRefresh Layout".\n\nOriginal site: ${metadata.url} | Industry: ${metadata.industry}\n`
      );
      break;
    }
    case "squarespace": {
      archive.append(Buffer.from(layoutHtml, "utf-8"), { name: "template.html" });
      archive.append(Buffer.from(layoutCss, "utf-8"), { name: "styles.css" });
      archive.append(
        Buffer.from(buildPreviewDocument(layoutHtml, layoutCss), "utf-8"),
        { name: "preview.html" }
      );
      addReadme(
        archive,
        "squarespace",
        `# Squarespace Export – Full Page\n\nGenerated by [pagerefresh.ai](https://pagerefresh.ai)\n\nThis zip contains the **full page** (all sections). One Code Block + Custom CSS is everything you need to build the full site on Squarespace.\n\n## What's in this zip\n\n- **preview.html** – Open in your browser to see the full page with styling before pasting into Squarespace.\n- **template.html** – Full page HTML to paste into one Code Block.\n- **styles.css** – CSS to paste into Design → Custom CSS.\n\n## Setup\n\n1. Open \`preview.html\` in a browser to see how the full page looks.\n2. In Squarespace: enable Developer Mode (Settings → Advanced → Developer Mode).\n3. Add a Code Block; paste the contents of \`template.html\` (this is the full page).\n4. Go to Design → Custom CSS and paste the contents of \`styles.css\`.\n\nOriginal site: ${metadata.url} | Industry: ${metadata.industry}\n`
      );
      break;
    }
    case "wix": {
      archive.append(Buffer.from(layoutHtml, "utf-8"), { name: "template.html" });
      archive.append(Buffer.from(layoutCss, "utf-8"), { name: "styles.css" });
      archive.append(
        Buffer.from(buildPreviewDocument(layoutHtml, layoutCss), "utf-8"),
        { name: "preview.html" }
      );
      addReadme(
        archive,
        "wix",
        `# Wix (Velo) Export – Full Page\n\nGenerated by [pagerefresh.ai](https://pagerefresh.ai)\n\nThis zip contains the **full page** (all sections). One HTML embed + CSS is everything you need to build the full site on Wix.\n\n## What's in this zip\n\n- **preview.html** – Open in your browser to see the full page with styling before adding to Wix.\n- **template.html** – Full page HTML to paste into an HTML/Embed element.\n- **styles.css** – CSS to add via Settings → Custom Code → Head or the page CSS panel.\n\n## Setup\n\n1. Open \`preview.html\` in a browser to see how the full page looks.\n2. In Wix Editor: enable Dev Mode (Developer → Enable).\n3. Add an HTML/Embed element; paste the contents of \`template.html\` (this is the full page).\n4. Add the contents of \`styles.css\` via Settings → Custom Code → Head, or the page CSS panel.\n\nOriginal site: ${metadata.url} | Industry: ${metadata.industry}\n`
      );
      break;
    }
    default: {
      throw new Error(`Unknown platform: ${String(platform)}`);
    }
  }

  await archive.finalize();
  const buffer = await bufferPromise;
  return {
    filename,
    buffer,
    contentType: "application/zip",
  };
}
