/**
 * Platform-specific layout exports (ZIP packages for self-installers).
 */

import archiver from "archiver";
import { Writable } from "stream";

export type Platform = "html" | "squarespace" | "wordpress" | "wix";

export interface ExportResult {
  filename: string;
  buffer: Buffer;
  contentType: string;
}

export interface ExportMetadata {
  url: string;
  industry: string;
  score: number;
}

function bufferFromStream(
  archive: archiver.Archiver
): Promise<Buffer> {
  const chunks: Buffer[] = [];
  const collector = new Writable({
    write(chunk: Buffer | string, _enc, cb) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk, "utf-8"));
      cb();
    },
  });
  archive.pipe(collector);
  return new Promise((resolve, reject) => {
    collector.on("finish", () => resolve(Buffer.concat(chunks)));
    archive.on("error", reject);
  });
}

function addReadme(
  archive: archiver.Archiver,
  platform: string,
  content: string
): void {
  archive.append(Buffer.from(content, "utf-8"), { name: "README.md" });
}

export async function exportLayout(
  platform: Platform,
  layoutHtml: string,
  layoutCss: string,
  templateName: string,
  metadata: ExportMetadata
): Promise<ExportResult> {
  const safeName = templateName.replace(/[^a-z0-9-_]/gi, "-").toLowerCase();
  const filename = `pagerefresh-layout${safeName}-${platform}.zip`;
  const archive = archiver("zip", { zlib: { level: 9 } });

  const bufferPromise = bufferFromStream(archive);

  const fullHtml =
    layoutHtml.trim().startsWith("<!") ||
    layoutHtml.trim().toLowerCase().startsWith("<html")
      ? layoutHtml
      : `<!DOCTYPE html><html><head><meta charset="utf-8"><link rel="stylesheet" href="styles.css"></head><body>${layoutHtml}</body></html>`;

  switch (platform) {
    case "html": {
      const htmlForExport =
        fullHtml.includes("styles.css") ? fullHtml : fullHtml.replace("</head>", "<link rel=\"stylesheet\" href=\"styles.css\"></head>");
      archive.append(Buffer.from(htmlForExport, "utf-8"), {
        name: "index.html",
      });
      archive.append(Buffer.from(layoutCss, "utf-8"), { name: "styles.css" });
      addReadme(
        archive,
        "html",
        `# Layout Export – HTML/CSS\n\nGenerated by [pagerefresh.ai](https://pagerefresh.ai)\n\n## Setup\n\n1. Upload \`index.html\` and \`styles.css\` to your web host or static hosting.\n2. Ensure paths to fonts/images match your setup (update any YOUR_* placeholders if present).\n3. Original site analyzed: ${metadata.url}\n4. Industry: ${metadata.industry} | Score: ${metadata.score}/100\n`
      );
      break;
    }
    case "wordpress": {
      const themeName = `PageRefresh ${safeName}`;
      const styleCss = `/*
Theme Name: ${themeName}
Description: Homepage layout generated by pagerefresh.ai
Author: pagerefresh.ai
Version: 1.0
*/
${layoutCss}`;
      archive.append(Buffer.from(styleCss, "utf-8"), { name: "style.css" });
      const indexPhp = `<?php
/**
 * Template Name: PageRefresh Layout
 * Generated by pagerefresh.ai
 */
get_header();
?>
${layoutHtml}
<?php
get_footer();
`;
      archive.append(Buffer.from(indexPhp, "utf-8"), { name: "index.php" });
      const functionsPhp = `<?php
/**
 * Enqueue theme styles – pagerefresh.ai
 */
function pagerefresh_enqueue_styles() {
  wp_enqueue_style('pagerefresh-layout', get_stylesheet_uri());
}
add_action('wp_enqueue_scripts', 'pagerefresh_enqueue_styles');
`;
      archive.append(Buffer.from(functionsPhp, "utf-8"), {
        name: "functions.php",
      });
      addReadme(
        archive,
        "wordpress",
        `# WordPress Theme Export\n\nGenerated by [pagerefresh.ai](https://pagerefresh.ai)\n\n## Upload\n\n1. Zip this folder (if you received individual files, ensure style.css, index.php, functions.php are in the root of the ZIP).\n2. In WordPress: Appearance → Themes → Add New → Upload Theme.\n3. Choose the ZIP and Activate (or use as a child theme).\n4. Create a Page and set Template to "PageRefresh Layout".\n\nOriginal site: ${metadata.url} | Industry: ${metadata.industry} | Score: ${metadata.score}/100\n`
      );
      break;
    }
    case "squarespace": {
      archive.append(Buffer.from(layoutHtml, "utf-8"), { name: "template.html" });
      archive.append(Buffer.from(layoutCss, "utf-8"), { name: "styles.css" });
      addReadme(
        archive,
        "squarespace",
        `# Squarespace Export\n\nGenerated by [pagerefresh.ai](https://pagerefresh.ai)\n\n## Setup\n\n1. Enable Developer Mode: Settings → Advanced → Developer Mode → enable.\n2. HTML: Add a Code Block or use Code Injection; paste contents of \`template.html\`.\n3. CSS: Design → Custom CSS; paste contents of \`styles.css\`.\n\nOriginal site: ${metadata.url} | Industry: ${metadata.industry} | Score: ${metadata.score}/100\n`
      );
      break;
    }
    case "wix": {
      archive.append(Buffer.from(layoutHtml, "utf-8"), { name: "template.html" });
      archive.append(Buffer.from(layoutCss, "utf-8"), { name: "styles.css" });
      addReadme(
        archive,
        "wix",
        `# Wix (Velo) Export\n\nGenerated by [pagerefresh.ai](https://pagerefresh.ai)\n\n## Setup\n\n1. In Wix Editor: Enable Dev Mode (Developer → Enable).\n2. Add an HTML/Embed element; paste contents of \`template.html\`.\n3. Add custom CSS via Settings → Custom Code → Head, or the page CSS panel. Paste \`styles.css\`.\n\nOriginal site: ${metadata.url} | Industry: ${metadata.industry} | Score: ${metadata.score}/100\n`
      );
      break;
    }
    default: {
      throw new Error(`Unknown platform: ${String(platform)}`);
    }
  }

  await archive.finalize();
  const buffer = await bufferPromise;
  return {
    filename,
    buffer,
    contentType: "application/zip",
  };
}
